apiVersion: v1
kind: Pod
metadata:
 name: test-pod
spec:
 containers:
 - name: test-container
   image: ubuntu
   volumeMounts:
   - mountPath: /mnt/disks/ssd-array
     name: ssd-array
   args:
   - sleep
   - "1000"
 nodeSelector:
   cloud.google.com/gke-local-ssd: "true"
 tolerations:
 - key: "local-ssd"
   operator: "Exists"
   effect: "NoSchedule"
 volumes:
 - name: ssd-array
   hostPath:
     path: /mnt/disks/ssd-array
